# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7920262aa9921f5aa8bfdb5c0ebc9d76f5d01f421951fa834d23bc5184cf579d9f00f74364b2a5fee5f1569b93edfe686894e99afa36a642d316db4ed8760d97

test:
  secret_key_base: 1890ca04d21d4f104481eedd197071aa8f91ee7dca729489eac20b7b4d2c633f89f887d44c2787defdd8aa97c5ab5ac1c61e35da04836c219b61a275c67e822e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
